name: Back-end
'on': workflow_dispatch
jobs: 
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install -g firebase-tools
      - run: npm install
        working-directory: "./back-end/functions"
      - run: firebase deploy --only functions --token ${{ secrets.FIREBASE_TOKEN }}
        working-directory: "./back-end"